logging:
  level:
    root: info


server:
  servlet:
    context-path: /
  port: 8079


spring:
  security:
    user:
      name: lxy
      password: lxy

  datasource:
    url: "jdbc:mysql://localhost:3306/lxy?useUnicode=true&characterEncoding=utf8"
    driver-class-name: com.mysql.jdbc.Driver
    username: "lxy"
    password: "123456"
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1

  redis:
    host: redis.domain
    port: 1234
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 200ms
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 1



mybatis:
  type-aliases-package: com.lxy.springboottemplate.domain


range: ${random.int(1,10)}

