package designpattern.dynamicproxypattern;

public class RealSubject implements AbstractSubject {

	@Override
	public void request(int a, int b) {
		// TODO Auto-generated method stub
		System.out.println("I'm generated by RealSubject!");
		System.out.println("a + b :" + (a + b));
	}

}
