version: '3.1'

services:
  kafka1:
    image: 'bitnami/kafka:latest'
    hostname: kafka1
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kz1:2181,kz2:2181,kz3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kz1
      - kz2
      - kz3

  kafka2:
    image: 'bitnami/kafka:latest'
    hostname: kafka2
    ports:
      - 9093:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kz1:2181,kz2:2181,kz3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kz1
      - kz2
      - kz3

  kafka3:
    image: 'bitnami/kafka:latest'
    hostname: kafka3
    ports:
      - 9094:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kz1:2181,kz2:2181,kz3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - kz1
      - kz2
      - kz3

  kz1:
    image: zookeeper
    restart: always
    hostname: kz1
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=kz1:2888:3888;2181 server.2=kz2:2888:3888;2181 server.3=kz3:2888:3888;2181


  kz2:
    image: zookeeper
    restart: always
    hostname: kz2
    ports:
      - 2185:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=kz1:2888:3888;2181 server.2=kz2:2888:3888;2181 server.3=kz3:2888:3888;2181


  kz3:
    image: zookeeper
    restart: always
    hostname: kz3
    ports:
      - 2186:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=kz1:2888:3888;2181 server.2=kz2:2888:3888;2181 server.3=kz3:2888:3888;2181
