package designpattern.proxypattern;

public class RealSubject extends AbstractSubject {

	@Override
	public void request() {
		// TODO Auto-generated method stub
		System.out.println("I'm generated by RealSubject!");
	}

}
