# Generated by Django 3.1 on 2020-10-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
